### ISSUE TITLE
Would you accept a pull request to remove use of Module::Signatures?

### ISSUE THREAD

**Issue by timbunce** [aanari/Plack-Middleware-NewRelic#2]
Firstly, thanks for writing NewRelic::Agent and Plack::Middleware::NewRelic, Ali!

I'm concerned about Plack::Middleware::NewRelic's use of Method::Signatures.

Method::Signatures has runtime dependencies on:
- Any::Moose (which is deprecated)
- Mouse (which we don't use and widely considered as deprecated by the community)
- Devel::Declare (which I think mst, the original author, once described as "sufficiently encapsulated insanity")
- PPI (which is very large)

All of which gets loaded into any app using Plack::Middleware::NewRelic (and the otherwise very lightweight NewRelic::Agent).

And for very little gain: simple signatures (using just HashRef, Str) on just four methods.

I'm offering to replace use of Module::Signatures with normal perl code and thus _greatly_ improve the startup time, _greatly_ reduce the memory footprint, and make it faster as well!

Would you accept a pull request from me for that?

**Comment by timbunce** [comment]
And now I look more closely I see that NewRelic::Agent loads Module::Signatures as well (it wasn't a declared dependency), but only has a single trivial method. So I extend my offer to NewRelic::Agent as well.

**Comment by timbunce** [comment]
Just as an extra data point, at $work we have >700 cpan distributions installed. (Including many big frameworks like DBIx::Class, Catalyst etc.) All of them are the latest, or nearly latest, releases. Currently _none_ uses Module::Signatures, so it's not installed at all.

**Comment by brianphillips** [comment]
:+1: to this request, please
